// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/gossip.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Membership struct {
	Endpoints   []*Membership_Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	VectorClock *VC                    `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock" json:"vector_clock,omitempty"`
}

func (m *Membership) Reset()                    { *m = Membership{} }
func (m *Membership) String() string            { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()               {}
func (*Membership) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Membership) GetEndpoints() []*Membership_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Membership) GetVectorClock() *VC {
	if m != nil {
		return m.VectorClock
	}
	return nil
}

type Membership_Endpoint struct {
	Ip   []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *Membership_Endpoint) Reset()                    { *m = Membership_Endpoint{} }
func (m *Membership_Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Membership_Endpoint) ProtoMessage()               {}
func (*Membership_Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0, 0} }

func (m *Membership_Endpoint) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Membership_Endpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type GossipRequest struct {
}

func (m *GossipRequest) Reset()                    { *m = GossipRequest{} }
func (m *GossipRequest) String() string            { return proto.CompactTextString(m) }
func (*GossipRequest) ProtoMessage()               {}
func (*GossipRequest) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func init() {
	proto.RegisterType((*Membership)(nil), "rpc.Membership")
	proto.RegisterType((*Membership_Endpoint)(nil), "rpc.Membership.Endpoint")
	proto.RegisterType((*GossipRequest)(nil), "rpc.GossipRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GossipService service

type GossipServiceClient interface {
	ReqForMembership(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*Membership, error)
}

type gossipServiceClient struct {
	cc *grpc.ClientConn
}

func NewGossipServiceClient(cc *grpc.ClientConn) GossipServiceClient {
	return &gossipServiceClient{cc}
}

func (c *gossipServiceClient) ReqForMembership(ctx context.Context, in *GossipRequest, opts ...grpc.CallOption) (*Membership, error) {
	out := new(Membership)
	err := grpc.Invoke(ctx, "/rpc.GossipService/ReqForMembership", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GossipService service

type GossipServiceServer interface {
	ReqForMembership(context.Context, *GossipRequest) (*Membership, error)
}

func RegisterGossipServiceServer(s *grpc.Server, srv GossipServiceServer) {
	s.RegisterService(&_GossipService_serviceDesc, srv)
}

func _GossipService_ReqForMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GossipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).ReqForMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.GossipService/ReqForMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).ReqForMembership(ctx, req.(*GossipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GossipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.GossipService",
	HandlerType: (*GossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqForMembership",
			Handler:    _GossipService_ReqForMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/gossip.proto",
}

func init() { proto.RegisterFile("rpc/gossip.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 225 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0x03, 0x31,
	0x10, 0xc7, 0xc9, 0xd6, 0xcf, 0xd9, 0x6a, 0xcb, 0x1c, 0x24, 0xec, 0x69, 0xe9, 0x69, 0xf1, 0x10,
	0x61, 0x05, 0x7d, 0x80, 0xe2, 0xc7, 0xc5, 0x4b, 0x04, 0xaf, 0x42, 0xe3, 0xa0, 0x41, 0xed, 0x4c,
	0x27, 0xb1, 0xcf, 0xe3, 0xa3, 0x4a, 0x53, 0x4b, 0xab, 0xb7, 0xf0, 0xff, 0x0a, 0xbf, 0x81, 0xb1,
	0x4a, 0xb8, 0x78, 0xe5, 0x94, 0xa2, 0x38, 0x51, 0xce, 0x8c, 0x03, 0x95, 0xd0, 0x9c, 0xad, 0xe4,
	0x25, 0x85, 0xcc, 0xfa, 0x1c, 0x3e, 0x38, 0xbc, 0xaf, 0xcd, 0xc9, 0xb7, 0x01, 0x78, 0xa0, 0xcf,
	0x19, 0x69, 0x7a, 0x8b, 0x82, 0x57, 0x70, 0x4c, 0xf3, 0x17, 0xe1, 0x38, 0xcf, 0xc9, 0x9a, 0x76,
	0xd0, 0xd5, 0xbd, 0x75, 0x2a, 0xc1, 0x6d, 0x33, 0xee, 0xe6, 0x37, 0xe0, 0xb7, 0x51, 0x3c, 0x87,
	0xe1, 0xee, 0xb8, 0xad, 0x5a, 0xd3, 0xd5, 0xfd, 0x61, 0xa9, 0x3e, 0x4d, 0x7d, 0xbd, 0x36, 0xa7,
	0x2b, 0xaf, 0x71, 0x70, 0xb4, 0x99, 0xc0, 0x53, 0xa8, 0xa2, 0x58, 0xd3, 0x9a, 0x6e, 0xe8, 0xab,
	0x28, 0x88, 0xb0, 0x27, 0xac, 0xb9, 0xf4, 0xf7, 0x7d, 0x79, 0x4f, 0x46, 0x70, 0x72, 0x57, 0x78,
	0x3c, 0x2d, 0xbe, 0x28, 0xe5, 0xfe, 0x7e, 0x23, 0x3c, 0x92, 0x2e, 0x63, 0x20, 0xbc, 0x86, 0xb1,
	0xa7, 0xc5, 0x2d, 0xeb, 0x0e, 0x09, 0x96, 0xbf, 0xff, 0x14, 0x9b, 0xd1, 0x3f, 0x94, 0xd9, 0x41,
	0x39, 0xc2, 0xe5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x80, 0x41, 0xcb, 0x5f, 0x35, 0x01, 0x00,
	0x00,
}
