// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/gossip.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	rpc/gossip.proto
	rpc/vector_clock.proto

It has these top-level messages:
	Membership
	VC
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Membership struct {
	Endpoints   []*Membership_Endpoint `protobuf:"bytes,1,rep,name=endpoints" json:"endpoints,omitempty"`
	VectorClock *VC                    `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock" json:"vector_clock,omitempty"`
}

func (m *Membership) Reset()                    { *m = Membership{} }
func (m *Membership) String() string            { return proto.CompactTextString(m) }
func (*Membership) ProtoMessage()               {}
func (*Membership) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Membership) GetEndpoints() []*Membership_Endpoint {
	if m != nil {
		return m.Endpoints
	}
	return nil
}

func (m *Membership) GetVectorClock() *VC {
	if m != nil {
		return m.VectorClock
	}
	return nil
}

type Membership_Endpoint struct {
	Ip    []byte `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port  int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
	Iport int32  `protobuf:"varint,3,opt,name=iport" json:"iport,omitempty"`
}

func (m *Membership_Endpoint) Reset()                    { *m = Membership_Endpoint{} }
func (m *Membership_Endpoint) String() string            { return proto.CompactTextString(m) }
func (*Membership_Endpoint) ProtoMessage()               {}
func (*Membership_Endpoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Membership_Endpoint) GetIp() []byte {
	if m != nil {
		return m.Ip
	}
	return nil
}

func (m *Membership_Endpoint) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func (m *Membership_Endpoint) GetIport() int32 {
	if m != nil {
		return m.Iport
	}
	return 0
}

func init() {
	proto.RegisterType((*Membership)(nil), "rpc.Membership")
	proto.RegisterType((*Membership_Endpoint)(nil), "rpc.Membership.Endpoint")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GossipService service

type GossipServiceClient interface {
	// Request paremeter should be used only for the new nodes connecting to the seed node
	// to make the seed node aware of them.
	// Any gossip request for membership should be requested with default-membership (empty)
	ReqForMembership(ctx context.Context, in *Membership, opts ...grpc.CallOption) (*Membership, error)
}

type gossipServiceClient struct {
	cc *grpc.ClientConn
}

func NewGossipServiceClient(cc *grpc.ClientConn) GossipServiceClient {
	return &gossipServiceClient{cc}
}

func (c *gossipServiceClient) ReqForMembership(ctx context.Context, in *Membership, opts ...grpc.CallOption) (*Membership, error) {
	out := new(Membership)
	err := grpc.Invoke(ctx, "/rpc.GossipService/ReqForMembership", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GossipService service

type GossipServiceServer interface {
	// Request paremeter should be used only for the new nodes connecting to the seed node
	// to make the seed node aware of them.
	// Any gossip request for membership should be requested with default-membership (empty)
	ReqForMembership(context.Context, *Membership) (*Membership, error)
}

func RegisterGossipServiceServer(s *grpc.Server, srv GossipServiceServer) {
	s.RegisterService(&_GossipService_serviceDesc, srv)
}

func _GossipService_ReqForMembership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Membership)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GossipServiceServer).ReqForMembership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.GossipService/ReqForMembership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GossipServiceServer).ReqForMembership(ctx, req.(*Membership))
	}
	return interceptor(ctx, in, info, handler)
}

var _GossipService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.GossipService",
	HandlerType: (*GossipServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReqForMembership",
			Handler:    _GossipService_ReqForMembership_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/gossip.proto",
}

func init() { proto.RegisterFile("rpc/gossip.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 223 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x49, 0xeb, 0xfa, 0x31, 0x5d, 0x75, 0x19, 0x44, 0x42, 0x4f, 0xc5, 0x53, 0xf1, 0x10,
	0xa1, 0x8a, 0x2f, 0xb0, 0xae, 0x9e, 0xbc, 0x44, 0xf0, 0x2a, 0x6c, 0x0c, 0x1a, 0xd4, 0x9d, 0x71,
	0x12, 0xf6, 0xd1, 0x7c, 0x3e, 0xd9, 0x54, 0x69, 0xe9, 0x2d, 0xf9, 0xfd, 0x3f, 0xc8, 0x3f, 0xb0,
	0x10, 0x76, 0x57, 0x6f, 0x14, 0x63, 0x60, 0xc3, 0x42, 0x89, 0xb0, 0x14, 0x76, 0xf5, 0xf9, 0x0e,
	0x6f, 0xbd, 0x4b, 0x24, 0x2f, 0xee, 0x93, 0xdc, 0x47, 0x2f, 0x5e, 0xfc, 0x28, 0x80, 0x47, 0xff,
	0xb5, 0xf6, 0x12, 0xdf, 0x03, 0xe3, 0x2d, 0x1c, 0xf9, 0xcd, 0x2b, 0x53, 0xd8, 0xa4, 0xa8, 0x55,
	0x53, 0xb6, 0x55, 0xa7, 0x8d, 0xb0, 0x33, 0x83, 0xc7, 0xac, 0xfe, 0x0c, 0x76, 0xb0, 0xe2, 0x25,
	0xcc, 0xc7, 0xe5, 0xba, 0x68, 0x54, 0x5b, 0x75, 0x07, 0x39, 0xfa, 0xbc, 0xb4, 0x55, 0x2f, 0x2e,
	0x77, 0x5a, 0x7d, 0x07, 0x87, 0xff, 0x15, 0x78, 0x02, 0x45, 0x60, 0xad, 0x1a, 0xd5, 0xce, 0x6d,
	0x11, 0x18, 0x11, 0xf6, 0x98, 0x24, 0xe5, 0xfc, 0xcc, 0xe6, 0x33, 0x9e, 0xc1, 0x2c, 0x64, 0x58,
	0x66, 0xd8, 0x5f, 0xba, 0x15, 0x1c, 0x3f, 0xe4, 0x95, 0x4f, 0x5e, 0xb6, 0xc1, 0x79, 0xbc, 0x81,
	0x85, 0xf5, 0xdf, 0xf7, 0x24, 0xa3, 0x39, 0xa7, 0x93, 0xb7, 0xd7, 0x53, 0xb0, 0xde, 0xcf, 0xdf,
	0x70, 0xfd, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x31, 0x51, 0x8f, 0x37, 0x01, 0x00, 0x00,
}
