// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc/node_service.proto

package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type SetRequest struct {
	Key          string        `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	ClockedValue *ClockedValue `protobuf:"bytes,2,opt,name=clocked_value,json=clockedValue" json:"clocked_value,omitempty"`
}

func (m *SetRequest) Reset()                    { *m = SetRequest{} }
func (m *SetRequest) String() string            { return proto.CompactTextString(m) }
func (*SetRequest) ProtoMessage()               {}
func (*SetRequest) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{0} }

func (m *SetRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetRequest) GetClockedValue() *ClockedValue {
	if m != nil {
		return m.ClockedValue
	}
	return nil
}

type ClockedValue struct {
	Value       *CacheValue `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	VectorClock *VC         `protobuf:"bytes,2,opt,name=vector_clock,json=vectorClock" json:"vector_clock,omitempty"`
}

func (m *ClockedValue) Reset()                    { *m = ClockedValue{} }
func (m *ClockedValue) String() string            { return proto.CompactTextString(m) }
func (*ClockedValue) ProtoMessage()               {}
func (*ClockedValue) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{1} }

func (m *ClockedValue) GetValue() *CacheValue {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ClockedValue) GetVectorClock() *VC {
	if m != nil {
		return m.VectorClock
	}
	return nil
}

type CacheValue struct {
	CType       uint32                 `protobuf:"varint,1,opt,name=c_type,json=cType" json:"c_type,omitempty"`
	StringValue string                 `protobuf:"bytes,2,opt,name=string_value,json=stringValue" json:"string_value,omitempty"`
	ListValue   []*CacheValue          `protobuf:"bytes,3,rep,name=list_value,json=listValue" json:"list_value,omitempty"`
	DictValue   map[string]*CacheValue `protobuf:"bytes,4,rep,name=dict_value,json=dictValue" json:"dict_value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *CacheValue) Reset()                    { *m = CacheValue{} }
func (m *CacheValue) String() string            { return proto.CompactTextString(m) }
func (*CacheValue) ProtoMessage()               {}
func (*CacheValue) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{2} }

func (m *CacheValue) GetCType() uint32 {
	if m != nil {
		return m.CType
	}
	return 0
}

func (m *CacheValue) GetStringValue() string {
	if m != nil {
		return m.StringValue
	}
	return ""
}

func (m *CacheValue) GetListValue() []*CacheValue {
	if m != nil {
		return m.ListValue
	}
	return nil
}

func (m *CacheValue) GetDictValue() map[string]*CacheValue {
	if m != nil {
		return m.DictValue
	}
	return nil
}

type SetResult struct {
}

func (m *SetResult) Reset()                    { *m = SetResult{} }
func (m *SetResult) String() string            { return proto.CompactTextString(m) }
func (*SetResult) ProtoMessage()               {}
func (*SetResult) Descriptor() ([]byte, []int) { return fileDescriptor2, []int{3} }

func init() {
	proto.RegisterType((*SetRequest)(nil), "rpc.SetRequest")
	proto.RegisterType((*ClockedValue)(nil), "rpc.ClockedValue")
	proto.RegisterType((*CacheValue)(nil), "rpc.CacheValue")
	proto.RegisterType((*SetResult)(nil), "rpc.SetResult")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for NodeService service

type NodeServiceClient interface {
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResult, error)
}

type nodeServiceClient struct {
	cc *grpc.ClientConn
}

func NewNodeServiceClient(cc *grpc.ClientConn) NodeServiceClient {
	return &nodeServiceClient{cc}
}

func (c *nodeServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResult, error) {
	out := new(SetResult)
	err := grpc.Invoke(ctx, "/rpc.NodeService/Set", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for NodeService service

type NodeServiceServer interface {
	Set(context.Context, *SetRequest) (*SetResult, error)
}

func RegisterNodeServiceServer(s *grpc.Server, srv NodeServiceServer) {
	s.RegisterService(&_NodeService_serviceDesc, srv)
}

func _NodeService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.NodeService/Set",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NodeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.NodeService",
	HandlerType: (*NodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _NodeService_Set_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rpc/node_service.proto",
}

func init() { proto.RegisterFile("rpc/node_service.proto", fileDescriptor2) }

var fileDescriptor2 = []byte{
	// 321 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x69, 0xeb, 0x26, 0x7d, 0xed, 0xa6, 0x06, 0x94, 0xb1, 0x83, 0xcc, 0x82, 0x32, 0x3c,
	0x54, 0x98, 0x28, 0x22, 0x78, 0x9a, 0x1e, 0xf5, 0x90, 0xc9, 0xae, 0x65, 0xbe, 0x3e, 0xb4, 0xac,
	0xac, 0x31, 0xcd, 0x06, 0xbd, 0xfb, 0x87, 0x4b, 0xf3, 0x36, 0x57, 0x65, 0x78, 0x4b, 0xf2, 0x7d,
	0xbf, 0xe4, 0xf1, 0xf2, 0xe0, 0x44, 0x2b, 0xbc, 0x5a, 0x14, 0x29, 0x25, 0x25, 0xe9, 0x55, 0x86,
	0x14, 0x2b, 0x5d, 0x98, 0x42, 0x78, 0x5a, 0x61, 0xdf, 0xc2, 0x15, 0xa1, 0x29, 0x74, 0x82, 0x79,
	0x81, 0x73, 0x86, 0xd1, 0x14, 0x60, 0x42, 0x46, 0xd2, 0xe7, 0x92, 0x4a, 0x23, 0x0e, 0xc1, 0x9b,
	0x53, 0xd5, 0x73, 0x06, 0xce, 0xd0, 0x97, 0xf5, 0x52, 0xdc, 0x42, 0xc7, 0xea, 0x94, 0x26, 0xab,
	0x59, 0xbe, 0xa4, 0x9e, 0x3b, 0x70, 0x86, 0xc1, 0xe8, 0x28, 0xd6, 0x0a, 0xe3, 0x31, 0x93, 0x69,
	0x0d, 0x64, 0x88, 0x8d, 0x5d, 0x34, 0x83, 0xb0, 0x49, 0xc5, 0x39, 0xb4, 0x38, 0xef, 0xd8, 0xfc,
	0x01, 0xe7, 0x67, 0xf8, 0x41, 0x9c, 0x66, 0x2a, 0x2e, 0x21, 0x6c, 0x16, 0xb9, 0x7e, 0x6d, 0xdf,
	0xda, 0xd3, 0xb1, 0x0c, 0x18, 0xda, 0x9b, 0xa3, 0x2f, 0x17, 0x60, 0x7b, 0x83, 0x38, 0x86, 0x36,
	0x26, 0xa6, 0x52, 0xfc, 0x44, 0x47, 0xb6, 0xf0, 0xb5, 0x52, 0x24, 0xce, 0x20, 0x2c, 0x8d, 0xce,
	0x16, 0xef, 0x8d, 0xfa, 0x7d, 0x19, 0xf0, 0x19, 0x27, 0x63, 0x80, 0x3c, 0x2b, 0xcd, 0x5a, 0xf0,
	0x06, 0xde, 0xae, 0x02, 0xfd, 0x5a, 0x61, 0xff, 0x01, 0x20, 0xcd, 0x70, 0xe3, 0xef, 0x59, 0xff,
	0xf4, 0x8f, 0x1f, 0x3f, 0x66, 0xc8, 0xfa, 0xd3, 0xc2, 0xe8, 0x4a, 0xfa, 0xe9, 0x66, 0xdf, 0x7f,
	0x86, 0xee, 0x6f, 0xb8, 0xa3, 0xed, 0x3f, 0xed, 0x72, 0xff, 0x6b, 0xd7, 0xbd, 0x7b, 0xe7, 0x44,
	0x01, 0xf8, 0xf6, 0x07, 0xcb, 0x65, 0x6e, 0x46, 0x37, 0x10, 0xbc, 0x14, 0x29, 0x4d, 0x78, 0x00,
	0xc4, 0x05, 0x78, 0x13, 0x32, 0x82, 0xe3, 0xdb, 0x7f, 0xee, 0x77, 0xb7, 0x07, 0x75, 0xec, 0xad,
	0x6d, 0x87, 0xe1, 0xfa, 0x3b, 0x00, 0x00, 0xff, 0xff, 0x56, 0x51, 0xe5, 0x42, 0x43, 0x02, 0x00,
	0x00,
}
